ktor:
  application:
    modules:
      - no.nav.tsm.ApplicationKt.module
  deployment:
    port: 8080
  database:
    jdbcUrl: $NAIS_DATABASE_TSM_REGISTER_TSM_REGISTER_JDBC_URL
  kafka:
    config:
      bootstrap.servers: $KAFKA_BROKERS
      security.protocol: "SSL"
      ssl.truststore.location: $KAFKA_TRUSTSTORE_PATH
      ssl.truststore.password: $KAFKA_CREDSTORE_PASSWORD
      ssl.truststore.type: "jks"
      ssl.keystore.location: $KAFKA_KEYSTORE_PATH
      ssl.keystore.password: $KAFKA_CREDSTORE_PASSWORD
      ssl.keystore.type: "PKCS12"
