apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: tsm
  name: tsm-register
  namespace: tsm
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-2-5120
        databases:
          - name: tsm-register
        diskAutoresize: true
        highAvailability: true
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  image: {{image}}
  port: 8080
  replicas:
    max: 10
    min: 10
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
  kafka:
    pool: nav-prod
